[package]
name = "anybytes"
version = "0.1.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/triblespace/anybytes"
description = "A small library abstracting over bytes owning types in an extensible way."

[dependencies]
bytes = { version = "1.6.0", features = ["serde"], optional = true }
memmap2 = { version = "0.9.4", optional = true }

[dev-dependencies]
quickcheck = "1.0"

[features]
default = ["frombytes", "frommmap"]
frombytes = ["bytes"]
frommmap = ["memmap2"]
